### ISSUE TITLE
Implement Logitech-provided HomeKit features

### ISSUE THREAD

**Issue by Nastras** [klanchman/homebridge-logi-circle-controls#14]
Hello @klanchman, would it be possible that you have all the functions Logitech offers put in your plugin? I mean the features that are included in the standard installation in HomeKit like the video stream, speakers, microphone and motion detectors.

The big advantage would be that only one device is displayed if you only connect the camera via your plugin.

Greeting Nastra

**Comment by klanchman** [comment]
Hi Nastras!

The original intention of this plugin was to extend the abilities that Logitech already exposes to HomeKit. Some features, like #11 if I get around to it, might start to blur that line though. I also like the idea of everything being grouped under a single device.

If implemented, this will take a considerable amount of effort. I have only dealt with the simple parts of Logitech's API (the switches), things like video and audio I'm sure will be more challenging, if they're possible at all. They'll also make the plugin much more susceptible to breaking due to Logitech changing their API, since it's not meant to be used by the public anyway. Problems like #13 could arise, but could take much longer to fix.

I'm going to leave this issue open, but I may not get around to investigating it for some time 😅

**Comment by Nastras** [comment]
Glad to hear that you like the idea. If you have a lot of time someday. Is it perhaps worth a try .-)

Thank you!

**Comment by Nastras** [comment]
Hi, @klanchman what is the current status, are you still developing the plugin?

Greetings Nastras

**Comment by klanchman** [comment]
Hi Nastras! I've mostly been keeping an eye out for bugs lately; there haven't been any new features I've wanted to add yet.

Looking over this issue again, it's unlikely I'll implement these features. There are a few reasons:

- the time it would take to develop them would be substantial
- the likelihood of the plugin breaking due to changes by Logitech would greatly increase
- the primary goal of the plugin is to provide features that Logitech does not already have in HomeKit

While I would also like to have everything grouped under a single device, I'm afraid the risks outweigh the benefits at this point. 😓 
If anything changes in the future I may revisit this, but for now I am going to close this issue.

**Comment by Nastras** [comment]
That's a shame but understandable.

Thanks for the info.
