### ISSUE TITLE
Reboot Switch

### ISSUE THREAD

**Issue by Nastras** [klanchman/homebridge-logi-circle-controls#15]
Hello @klanchman, I need to ask you something again. I've been having a problem lately that one or two cameras in homekit are unreachable.

Would it be possible to implement a reboot switch in your plugin via the api?

Thank you .-)

**Comment by klanchman** [comment]
Hi Nastras!

Logitech doesn’t provide a way to do that via the app or website. I watch the traffic from their apps to figure out what APIs are available since it’s not public. So I won’t be able to figure out if this is possible for the time being. The only time that a remote reboot might happen is during firmware updates, but I’m not sure. So I will try to sniff the traffic during the next firmware update (if another one happens) to see if this is something that can be done.

I actually had connection issues with my camera after updating to iOS 13. I used the “manual reset” option and that fixed it. I’d recommend you try that if you continue to have issues. You can find that by going to the camera in Logitech’s app and pressing the “Remove Camera” button. When it prompts you, pick the “Manual Reset” option and follow the instructions. 

Hopefully that helps in the meantime! I’ll leave this open in hopes that a firmware update happens sometime soon so I can see if rebooting via the API is possible.

**Comment by Nastras** [comment]
Thanks for the tip!

Nice that I am not alone with the problem 😄
I've completely resetted the cameras so far. If it happens again, I will try to do a manual reset.

I'll keep my fingers crossed that you'll find a way with the next firmware update.

**Comment by klanchman** [comment]
I didn't see anything in the public API for this, and haven't noticed anything in the internal API still. I'm guessing this won't be possible, so I'm closing this issue. If things change I'll reopen it 🙂
