### ISSUE TITLE
HomeKit secure video

### ISSUE THREAD

**Issue by QandnotU** [klanchman/homebridge-logi-circle-controls#19]
Looks like once the camera's firmware is updated and you move the camera into HomeKit secure video, you no longer can use the Logi app, which renders this plugin obsolete since its pulling from the Logi API. Do you know if the latest HomeKit API exposes anything that would give us control over the status light, night vision, or power in automations?

**Comment by klanchman** [comment]
Before moving on to the question at hand, I want to highlight an important point you made so that anyone who is thinking about upgrading their camera and sees this issue is aware:

**If you update your Logi Circle camera to use HomeKit Secure Video, this plugin will no longer work for that camera.**

HomeKit Secure Video currently supports the same toggles as this plugin, but does _not_ expose them for use with Automations.

**If you need the ability to automate things that this plugin exposes, I recommend not updating your camera to use HomeKit Secure Video.**

---

With that out of the way, on to your question:

> Do you know if the latest HomeKit API exposes anything that would give us control over the status light, night vision, or power in automations?

Unfortunately I do not know how to programmatically interact with a camera that uses HomeKit Secure Video. I only have 1 camera, so I'll be waiting to upgrade my camera until the firmware is out of beta (and I'd _really_ like if I could revert the firmware without contacting Logitech customer support). If/when I upgrade, I'll definitely be sniffing around to see how things work, but it may be a while before I upgrade.

Since I don't know how long I'll be waiting to update—and whether it'll even be feasible to expose the same functionality through HomeKit Secure Video—I'm going to mirror what Aron at Logitech is saying on [/r/HomeKit](https://www.reddit.com/r/HomeKit/): your best bet for now is to send feature suggestions for HomeKit Secure Video to Apple (https://www.apple.com/feedback/, probably the iPhone option since they don't have anything specifically for HomeKit currently).

Sorry I can't be of more help right now 😓 
Hopefully I will learn more relatively soon!

**Comment by QandnotU** [comment]
Thank you for the quick reply, I've already submitted feedback to Apple. Thank you again for the plugin, it served me well.

**Comment by konki-vienna** [comment]
> If you update your Logi Circle camera to use HomeKit Secure Video, this plugin will no longer work for that camera.

Is HomeKit Secure Video still making this plugin inoperable?
I have bought the [Logitech Circle View](https://www.logitech.com/de-at/products/cameras/circle-view-security-camera.961-000490.html) camera recently, but I do not manage to get the plugin to work.
Homebridge console says
`[Logi Circle Controls] Loaded remote accessories successfully`
but that's it.

**Comment by klanchman** [comment]
Correct, this plugin does not work with cameras using HomeKit Secure Video like the Circle View, Circle View Doorbell, and the Circle 2 HKSV beta firmware. The plugin relies on Logitech's web service for older Circle cameras, which HKSV cameras don't connect through.

I still don't know if you can communicate with HKSV cameras through Homebridge for things like controlling night vision and the status light. If it is possible, it'd make the most sense to be a different plugin since it wouldn't be specific to Logi Circle cameras 😄

**Comment by klanchman** [comment]
My Circle camera died, so I did some testing with Scrypted to emulate a HKSV camera to see how to make additional controls for it. The short version is that I won't be able to do it 😞 

I'm personally most interested in the ability to change recording settings on my camera through automations. One thing HKSV can't do right now is "record while I'm away, and also record at night regardless of where I am," which is something that I want to be able to do.

With that in mind, I looked at this from 2 angles: looking at HTTP calls to see how the Apple Home app is changing recording settings (in order to make a Homebridge plugin that can make those calls), and looking through Apple's [HomeKit SDK](https://developer.apple.com/documentation/homekit/) to see if recording settings can be changed through that (in order to make an app with Shortcuts integration).

For approach 1, I was pretty quickly shut down. Based on what I can see, it looks like changing recording settings in the Home app ends up communicating with Apple's `cloudd` daemon, which then makes an HTTP call to `gateway.icloud.com` which I assume changes the setting. Communications with `gateway.icloud.com` use certificate pinning, so looking at the HTTP calls is beyond my capabilities, so this is a dead end. (Even if I could see the calls, I assume they use an authentication mechanism that'd be very difficult to use in Homebridge plugin. The one this plugin uses right now is already painful enough for users to set up...)

For approach 2, I tossed together a small test project to see if recording settings get exposed in the stuff you can access via the HomeKit SDK. From what I could see the answer is "no," so also a dead end.

Approach 2 _should_ be able to modify night vision settings on supported cameras, and _might_ be able to toggle the LED status indicator, but these are not things I'm personally too interested in, and other apps might already provide them. My use case centers on recording, which it doesn't seem I can do anything with, so I'm not very interested in trying to build anything to handle the other things this plugin could do.

Unfortunately my best recommendations are to check out 3rd party HomeKit apps to see if any of them expose the kinds of functionality you're looking for, and to submit feedback to Apple asking them to add what you'd like to the Home app. If you're interested in changing recording settings via Shortcuts in particular, you can reference FB10727891 which I submitted.

Hopefully you're able to find something that does what you want! 😄

**Comment by konki-vienna** [comment]
Thank you!
________________________________
Von: Kyle Lanchman ***@***.***>
Gesendet: Sonntag, 17. Juli 2022 19:19
An: klanchman/homebridge-logi-circle-controls ***@***.***>
Cc: Demblin Konstantin G-LABS ***@***.***>; Comment ***@***.***>
Betreff: Re: [klanchman/homebridge-logi-circle-controls] HomeKit secure video (#19)


My Circle camera died, so I did some testing with Scrypted to emulate a HKSV camera to see how to make additional controls for it. The short version is that I won't be able to do it 😞

I'm personally most interested in the ability to change recording settings on my camera through automations. One thing HKSV can't do right now is "record while I'm away, and also record at night regardless of where I am," which is something that I want to be able to do.

With that in mind, I looked at this from 2 angles: looking at HTTP calls to see how the Apple Home app is changing recording settings (in order to make a Homebridge plugin that can make those calls), and looking through Apple's HomeKit SDK<https://urldefense.com/v3/__https://developer.apple.com/documentation/homekit/__;!!OMGRPR5eiCE28w!urhDvU-njZNfInVoPMUdmiqZJyoNhyXVD5v8OP-mtUtsed8vsqaEB6fWWOhqHRfYyUQeFu8GBYCikefO4Ul8hwwmHA_8N-gj$> to see if recording settings can be changed through that (in order to make an app with Shortcuts integration).

For approach 1, I was pretty quickly shut down. Based on what I can see, it looks like changing recording settings in the Home app ends up communicating with Apple's cloudd daemon, which then makes an HTTP call to gateway.icloud.com which I assume changes the setting. Communications with gateway.icloud.com use certificate pinning, so looking at the HTTP calls is beyond my capabilities, so this is a dead end. (Even if I could see the calls, I assume they use an authentication mechanism that'd be very difficult to use in Homebridge plugin. The one this plugin uses right now is already painful enough for users to set up...)

For approach 2, I tossed together a small test project to see if recording settings get exposed in the stuff you can access via the HomeKit SDK. From what I could see the answer is "no," so also a dead end.

Approach 2 should be able to modify night vision settings on supported cameras, and might be able to toggle the LED status indicator, but these are not things I'm personally too interested in, and other apps might already provide them. My use case centers on recording, which it doesn't seem I can do anything with, so I'm not very interested in trying to build anything to handle the other things this plugin could do.

Unfortunately my best recommendations are to check out 3rd party HomeKit apps to see if any of them expose the kinds of functionality you're looking for, and to submit feedback to Apple asking them to add what you'd like to the Home app. If you're interested in changing recording settings via Shortcuts in particular, you can reference FB10727891 which I submitted.

Hopefully you're able to find something that does what you want! 😄
