### ISSUE TITLE
Switch for alarm messages and night modus ?

### ISSUE THREAD

**Issue by Nastras** [klanchman/homebridge-logi-circle-controls#7]
Hi @klanchman 
because now everything is running I wanted to ask if it is it possible that you also insert a switch for the alarm message function and the night modus?

![img_1573](https://user-images.githubusercontent.com/27686185/46280956-9a8f7480-c56d-11e8-8cba-2b0ae655544c.jpg)

Greeting Nastra

**Comment by klanchman** [comment]
Hi!

I did a little research, and I think the alerts will not be practical to manage with this plugin. It looks like alerts are configured per device. For instance, my phone has alerts enabled, but my tablet does not. It’s likely there is some device identifier that Logitech uses to do this. It’s probably possible to capture the information needed using a debugging proxy server, but walking users through that would be pretty difficult. 

My suggestion for that would be to leverage the privacy mode switch if possible. When privacy mode is enabled, you won’t receive notifications (although the camera will also not record events, which may not be ideal for everyone). I have my camera configured to go into privacy mode when I arrive home, for instance 😄 

---

Night vision mode may be possible. It will take a little research into how to do it with Homebridge, since it’s a 3 way switch, rather than just 2 way. I’m not sure when I’ll be able to get around to that, it may take a little while for me to get some free time 😞

Thanks!

**Comment by klanchman** [comment]
Update on the night vision switch.

I was hoping there'd be some way to expose a single switch with multiple positions (in this case something like Off, Window, and Unobstructed). Unfortunately, I don't see a way to do that currently.

I think about the only option I have is to expose 3 switches that act like a radio button group, something like [the homebridge-switcheroo multiswitch](https://github.com/chriszelazo/homebridge-switcheroo#multiswitch-radio-buttons).

This will be particularly ugly in the Home app, since it doesn't group accessories at all, but other apps it should make a little bit of sense I hope. I'll probably set it up to be disabled by default to hide the clutter.

Planning to do this as part of 2.1.0!

**Comment by klanchman** [comment]
Hi @Nastras! 

I published a new beta of the package that has new switches for night mode.

You can install the beta like this:

```
npm i -g homebridge-logi-circle-controls@next
```

You can find the README for the beta version [here](https://github.com/klanchman/homebridge-logi-circle-controls/blob/feature/7-night-vision/README.md).

Please note that the switches are disabled by default, you need to explicitly enable it in your config.

There are other changes as part of this version, so you may see a couple of warnings when running it.

I broke up night vision into 2 switches because Logitech handles it like that on their API, and it made it pretty quick to implement in the plugin.

Let me know if you run into any issues with the beta!

**Comment by Nastras** [comment]
Hello @klanchman ,

Sorry it took a little longer until I could test it. But now I have tried it. Everything works. I think you can post the update! Great work, thank you!

**Comment by klanchman** [comment]
Thanks for testing! This is now available in [2.1.0](
https://github.com/klanchman/homebridge-logi-circle-controls/releases/tag/2.1.0)!
